FROM openjdk:8-jre
MAINTAINER Frankie Robertson <frankie@robertson.name>

RUN apt-get update && apt-get install -y \
    git \
  && apt-get update \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY fetch-drive.sh /usr/bin/
RUN chmod +x /usr/bin/fetch-drive.sh
