FROM frankierr/mateplus:base
MAINTAINER Frankie Robertson <frankie@robertson.name>

RUN git clone https://github.com/microth/mateplus.git

COPY parse.sh fetch-core-reqs.sh /mateplus/scripts/
RUN chmod +x /mateplus/scripts/*.sh

RUN cd mateplus && \
  ./scripts/fetch-core-reqs.sh && \
  rm ./scripts/fetch-core-reqs.sh

CMD cd mateplus && \
  tee in.txt && \
  ./scripts/parse.sh in.txt && \
  cat out.txt && \
  rm in.txt out.txt
