RUN git clone https://github.com/microth/PathLSTM.git

COPY fetch-pathltsm-reqs.sh /PathLSTM/scripts/
COPY parse-pathltsm.sh /PathLSTM/scripts/parse.sh
RUN chmod +x /PathLSTM/scripts/*.sh

RUN cd PathLSTM && \
  ./scripts/fetch-pathlstm-reqs.sh && \
  rm ./scripts/fetch-pathlstm-reqs.sh

CMD cd PathLSTM && \
  tee in.txt && \
  ./scripts/parse.sh in.txt && \
  cat out.txt && \
  rm in.txt out.txt
